VERBOSE = 0
INTERVAL = 0.9
LOG_PATH = "/soundmeter"
FILE_LOG = ""
DATA_HTML = ""
INTERFACE="wlan1"
VENDOR_ID = 0x0cf3
PRODUCT_ID = 0x9271

MONITOR_INTERFACE = "mon0"
WIFI_DATAPATH_CSV = "/wifi_sensed"
WIFI_SCANNER_LOGGING = "/var/log/wifi_scanner.log"
WIFI_SENSING_TIME = 300 
